[buildPlans.IosevkaCkt]
family = "Iosevka CKT"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

	[buildPlans.IosevkaCkt.variants.design]
	one = "base"
	four = "closed-serifless"
	seven = "straight-serifless"
	zero = "oval-tall-slashed"
	capital-q = "crossing-baseline"
	f = "flat-hook-serifless-crossbar-at-x-height"
	i = "hooky"
	l = "serifed-flat-tailed"
	t = "flat-hook"
	cyrl-a = "double-storey-hook-inward-serifed-toothless-corner"
	cyrl-ve = "standard-unilateral-serifed"
	cyrl-capital-ze = "unilateral-serifed"
	cyrl-ze = "unilateral-serifed"
	cyrl-capital-ka = "symmetric-connected-top-left-serifed"
	cyrl-ka = "symmetric-connected-top-left-serifed"
	cyrl-em = "flat-bottom-motion-serifed"
	cyrl-capital-en = "top-left-serifed"
	cyrl-en = "top-left-serifed"
	cyrl-capital-er = "closed-motion-serifed"
	cyrl-er = "eared-motion-serifed"
	cyrl-capital-u = "straight-motion-serifed"
	cyrl-u = "straight-motion-serifed"
	cyrl-capital-e = "unilateral-bottom-serifed"
	cyrl-e = "unilateral-bottom-serifed"
	asterisk = "penta-low"
	at = "fourfold"
	percent = "rings-continuous-slash"
	lig-neq = "slightly-slanted-dotted"
	lig-hyphen-chain = "with-notch"
	lig-plus-chain = "with-notch"
	lig-double-arrow-bar = "with-notch"
	lig-single-arrow-bar = "with-notch"

	[buildPlans.IosevkaCkt.ligations]
	inherits = "dlig"

	[buildPlans.IosevkaCkt.slopes.Upright]
	angle = 0
	shape = "upright"
	menu = "upright"
	css = "normal"

	[buildPlans.IosevkaCkt.slopes.Oblique]
	angle = 9.4
	shape = "oblique"
	menu = "oblique"
	css = "oblique"


[buildPlans.IosevkaCktFixedSpacing]
family = "Iosevka CKT Fixed Spacing"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

	[buildPlans.IosevkaCktFixedSpacing.variants.design]
	one = "base"
	four = "closed-serifless"
	seven = "straight-serifless"
	zero = "oval-tall-slashed"
	capital-q = "crossing-baseline"
	f = "flat-hook-serifless-crossbar-at-x-height"
	i = "hooky"
	l = "serifed-flat-tailed"
	t = "flat-hook"
	cyrl-a = "double-storey-hook-inward-serifed-toothless-corner"
	cyrl-ve = "standard-unilateral-serifed"
	cyrl-capital-ze = "unilateral-serifed"
	cyrl-ze = "unilateral-serifed"
	cyrl-capital-ka = "symmetric-connected-top-left-serifed"
	cyrl-ka = "symmetric-connected-top-left-serifed"
	cyrl-em = "flat-bottom-motion-serifed"
	cyrl-capital-en = "top-left-serifed"
	cyrl-en = "top-left-serifed"
	cyrl-capital-er = "closed-motion-serifed"
	cyrl-er = "eared-motion-serifed"
	cyrl-capital-u = "straight-motion-serifed"
	cyrl-u = "straight-motion-serifed"
	cyrl-capital-e = "unilateral-bottom-serifed"
	cyrl-e = "unilateral-bottom-serifed"
	asterisk = "penta-low"
	at = "fourfold"
	percent = "rings-continuous-slash"
	lig-neq = "slightly-slanted-dotted"
	lig-hyphen-chain = "with-notch"
	lig-plus-chain = "with-notch"
	lig-double-arrow-bar = "with-notch"
	lig-single-arrow-bar = "with-notch"

	[buildPlans.IosevkaCktFixedSpacing.ligations]
	inherits = "dlig"

	[buildPlans.IosevkaCktFixedSpacing.slopes.Upright]
	angle = 0
	shape = "upright"
	menu = "upright"
	css = "normal"

	[buildPlans.IosevkaCktFixedSpacing.slopes.Oblique]
	angle = 9.4
	shape = "oblique"
	menu = "oblique"
	css = "oblique"